### ISSUE TITLE
can't use discord own emoji

### ISSUE THREAD

**Issue by alan67160** [BeepIsla/discord-customstatus#10]
```js
{
	"token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"handleRatelimit": true,
	"animation": [
		{
			"text": "1",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "2",
			"emojiID": "846445521039392778",
			"emojiName": "dango",
			"timeout": 2000
		}
	]
}
```

**Comment by BeepIsla** [comment]
Are you sure this is the correct emoji ID? Make sure when you type `\:dango:` it actually returns that ID

**Comment by alan67160** [comment]
![image](https://user-images.githubusercontent.com/20385640/119394042-52b45180-bd04-11eb-9b00-61903654c5fa.png)
:dango:
846445521039392778

**Comment by alan67160** [comment]
you can try it by yourself too

**Comment by BeepIsla** [comment]
Oh I didn't know dango was a built in default emoji. Set `emojiID` to `null` and set `emojiName` to the unicode (Result of `\:dango:`)

**Comment by alan67160** [comment]
Error
```
[ .........] / postinstall:container: timing audit body Completed in 1m internal/modules/cjs/loader.js:1114
throw err;
SyntaxError: /home/container/config.json: Unexpected token : in JSON at position 617
at parse (<anonymous>)
at Object.Module._extensions..json (internal/modules/cjs/loader.js:1111:22)
at Module.load (internal/modules/cjs/loader.js:933:32)
at Function.Module._load (internal/modules/cjs/loader.js:774:14)
at Module.require (internal/modules/cjs/loader.js:957:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object.<anonymous> (/home/container/index.js:2:16)
at Module._compile (internal/modules/cjs/loader.js:1068:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
at Module.load (internal/modules/cjs/loader.js:933:32)
```

**Comment by BeepIsla** [comment]
There is an error somewhere in your config, post it again or use https://jsonlint.com/ to find the error yourself

**Comment by alan67160** [comment]
![image](https://user-images.githubusercontent.com/20385640/119394982-775cf900-bd05-11eb-8859-c95a8c869220.png)

**Comment by alan67160** [comment]
```
{
	"token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"handleRatelimit": true,
	"animation": [{
			"text": "text1",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text2",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text3",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text4",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text5",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": null,
			"emojiID": null,
			"emojiName": "\:dango:",
			"timeout": 1000
		}
	]
}
```

**Comment by BeepIsla** [comment]
I said use the unicode, the result you get when you type `\:dango:` in Discord. Look at the example: https://github.com/BeepIsla/discord-customstatus/issues/10#issuecomment-847262560

**Comment by alan67160** [comment]
I don't know what you mean by that
`\:dango:` UTF-8 to unicode is still `\:dango:`

**Comment by alan67160** [comment]
![image](https://user-images.githubusercontent.com/20385640/119395649-6a8cd500-bd06-11eb-872c-e8019205a26c.png)

**Comment by BeepIsla** [comment]
The unicode of an emoji is like a normal character but it represents an emoji, not convert a UTF8 string into a Unicode string, that is something else. Again, look at the example I gave you here https://github.com/BeepIsla/discord-customstatus/issues/10#issuecomment-847262560:

> ```json
> {
>     "text": "2",
>     "emojiID": null,
>     "emojiName": "🍡",
>     "timeout": 2000
> }
> ```

You can just straight up copy & paste this.

**Comment by alan67160** [comment]
```
{
	"token": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
	"handleRatelimit": true,
	"animation": [{
			"text": "text1",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text2",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text3",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text4",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": "text5",
			"emojiID": null,
			"emojiName": null,
			"timeout": 1000
		},
		{
			"text": null,
			"emojiID": null,
			"emojiName": "\ud83c\udf61",
			"timeout": 1000
		}
	]
}
```
still not working

**Comment by alan67160** [comment]
oh it work now, Thanks
